### ISSUE TITLE
Support for Pluto+

### ISSUE THREAD

**Issue by Derek000** [F1ATB/Remote-SDR#19]
Hi,

I recently purchased a PlutoSDR+. Is there a way to utilise this without downgrading the firmware?

I was also thinking this could be a good single device option as a cross linked repeater. Perhaps future options for DMR or DStar.

https://github.com/plutoplus/plutoplus

PLUTO+ https://a.aliexpress.com/_msFNOzS

Thanks again.
Derek

**Comment by F1ATB** [comment]
Pluto + is not yet in the Road Map. I don't see the interest for 2 TX and 2 RX.
May be one day in the future.

**Comment by tomvdb** [comment]
+1 for pluto + 2tx and 2rx support :)
