### ISSUE TITLE
Problem with audio.

### ISSUE THREAD

**Issue by ombi61** [F1ATB/Remote-SDR#21]
Hi,
I install rev 4.4 on the Raspberry pi4 image with a RTL SDR as receiver. 
The remote SDR  (http://192.168.xx.xx) seems to work properly but  no audio is received even if i switch on  FM band where there are several strong signal,
Any suggestion?
Thanks

**Comment by F1ATB** [comment]
Did you set the authorization as explained here:
https://f1atb.fr/index.php/2022/01/06/microphone-and-signal-processing-authorization/

**Comment by ombi61** [comment]
You are right!!!!
Now it  works!
Now the problem is that my hackRF box is not viewed by remote-sdr, with
lsusb i find the small R820T2 sdr (RX) but no hackRF...TX..
73

Il giorno dom 6 feb 2022 alle ore 14:35 F1ATB ***@***.***> ha
scritto:

**Comment by F1ATB** [comment]
Probably a blocking situation between the HackRF and RPI on the USB. Power off a few second, then On.

**Comment by F1ATB** [comment]
You must see the green light (USB)  on the hackrf,
