### ISSUE TITLE
Supported browsers?

### ISSUE THREAD

**Issue by sh123** [F1ATB/Remote-SDR#34]
Running Remote-SDR on RPI 4 with Bullseye distro, running Debian Bullseye on PC.

Receive works, but when trying to transmit:
- No errors from nodejs console
- Latest Firefox (102.9.0esr) shows "SDR TX On" with green, microphone is selected, clicking on "TX audio on" makes button red, but no TX signal is shown on spectrogram. Firerefox does not pick any mic audio, there is error on console
```
Uncaught DOMException: AudioContext.createMediaStreamSource: Connecting AudioNodes from AudioContexts with different sample-rate is currently not supported.
Micro Stream not ready
```
Changing sample rate from 10000 to 44100 in `public/JS/remote_TX_audio.js` solves this issue and transmission is performing, but with **very noticeable delay** and high CPU usage by python running gnuradio blocks.
![image](https://user-images.githubusercontent.com/1933302/233858173-f48ff544-febd-4e10-999d-9f7abc914cef.png)
- Trying with latest Chrome (112.0.5615.165), "SDR TX On" is shown with blue, clicking on "TX audio" button does not turn it red, mic signal is visible on spectrogram, so it picks up mic audio, but cannot start transmission
![image](https://user-images.githubusercontent.com/1933302/233858232-100b02fc-49e6-4767-8613-e74cb31b7c9f.png)
- Also in chrome "select frequency band" does not work, old band selections is selected back when trying to select new band
- Transmit works on RPI4 with, e.g. SDRAngel, GNURadio and command line tools

**Comment by F1ATB** [comment]
As mentioned in the documentation, don't use Firefox. Use Chrome or Edge browsers.
If you still have some issues. Go to the troubleshooting page :
https://f1atb.fr/index.php/2022/02/15/troubleshooting/
You will find different issues and how to solve them.
Regards 73
André F1ATB

**Comment by sh123** [comment]
Google Chrome works fine for transmit. Haven't realized that pin code should be set in settings to enable transmit. Thank you.
