### ISSUE TITLE
Lost ability manage GPIO pin with TX/RX state change

### ISSUE THREAD

**Issue by Sergey-R5AU** [F1ATB/Remote-SDR#40]
Hi Andre !

after some updates of Pluto i lost ability to driving GPIO with changing RX/TX state with:
![RX](https://github.com/F1ATB/Remote-SDR/assets/85807500/eb812411-8c6d-47c6-bfa2-a331bbad784b)
![TX](https://github.com/F1ATB/Remote-SDR/assets/85807500/e7ad58f7-ebc3-4d08-99a1-b4046f38d590)

I have tested separately onoff package with simple JS script like:

'use strict';
const Gpio = require('onoff').Gpio;  
const led = new Gpio(6, 'out');  
led.writeSync(1);     

GPIO6 driving fine as previously , but state not changing with TX/RX RemSDR  - with **TX Audio** button or with external switch based on arduino. 

What could be wrong, what i can trace and check ?

Thank you !

![common](https://github.com/F1ATB/Remote-SDR/assets/85807500/e32d2deb-e833-435a-9c7e-c6dc9bd9e223)

**Comment by Sergey-R5AU** [comment]
I have been spending a time for isolation and solving problem above.
Even on the last version completely lost TX audio !
On the fact:  core of issue is -  version of the Browsers ,  Chrome or Edge.
I roll back to the version of the Chrome 110.xx - all works fine.
Problem:  new version are not supporting used node.js and especially incompatible with used version of socket.io
Recommended to use latest version of node.js and t libraries.
Problem solved.

**Comment by Sergey-R5AU** [comment]
Problem solved as mentioned in the last post. Latest versions of browsers are not supporting used version of node.js and socket.io with used in RemSDR images.

**Comment by dona76** [comment]
Very nice software André !
I've fixed the TX issue with rolling back Chrome to 104 version (ether 32 or 64b) and following method 1 in 
https://www.browserstack.com/guide/downgrade-to-older-versions-of-chrome
With Group Policy, it is possible to disable gogole update.
73' F4BSP
