### ISSUE TITLE
SDRPlay support?

### ISSUE THREAD

**Issue by jkrnl** [F1ATB/Remote-SDR#5]
Hi,
Thank you for all effort making this Remote SDR available for HAMs!
I was wondering if can get support some day for famous SDRPlay receivers to cover most of the SDRs available nowadays.

Cheers,
73 DX HG0NCL
Kornel

**Comment by F1ATB** [comment]
It's in my wishing list to address this type of sdr. Sure this winter. 73
F1ATB

**Comment by jkrnl** [comment]
Cool,good to hear that! Thank you!
